"use client";

import { FormEvent, useState } from "react";
import { EmptyState } from "@/components/ui/empty-state";
import type { CricketMatch, MatchStatus } from "@/lib/types";

type MatchForm = Pick<CricketMatch, "homeTeam" | "awayTeam" | "date" | "location" | "overs">;
const emptyForm: MatchForm = { homeTeam: "Green Giants", awayTeam: "", date: "", location: "", overs: 20 };

export function MatchesClient({ initialMatches }: { initialMatches: CricketMatch[] }) {
  const [matches, setMatches] = useState(initialMatches);
  const [activeFilter, setActiveFilter] = useState<MatchStatus | "All">("All");
  const [form, setForm] = useState<MatchForm>(emptyForm);
  const [isFormOpen, setIsFormOpen] = useState(false);
  const visibleMatches = activeFilter === "All" ? matches : matches.filter((match) => match.status === activeFilter);
  function submitMatch(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!form.awayTeam.trim() || !form.date || !form.location.trim()) return; setMatches((current) => [{ id: crypto.randomUUID(), ...form, awayTeam: form.awayTeam.trim(), location: form.location.trim(), status: "Upcoming" }, ...current]); setForm(emptyForm); setIsFormOpen(false); }
  return <>
    <div className="mb-5 flex gap-3 overflow-x-auto pb-1">{(["All", "Upcoming", "Live", "Completed"] as const).map((filter) => <button key={filter} onClick={() => setActiveFilter(filter)} className={`min-h-9 shrink-0 rounded-full px-4 text-sm font-semibold ${activeFilter === filter ? "bg-[var(--brand)] text-white" : "border border-[var(--line)] bg-white text-[var(--muted)]"}`}>{filter}</button>)}<button onClick={() => setIsFormOpen(true)} className="ml-auto min-h-9 shrink-0 rounded-full bg-[var(--accent)] px-4 text-sm font-bold text-stone-900">+ New match</button></div>
    <div className="space-y-3">{visibleMatches.length ? visibleMatches.map((match) => <article key={match.id} className="rounded-2xl border border-[var(--line)] bg-white p-4"><div className="flex items-center justify-between gap-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${match.status === "Live" ? "bg-red-50 text-red-700" : match.status === "Completed" ? "bg-stone-100 text-stone-600" : "bg-emerald-50 text-[var(--brand)]"}`}>{match.status}</span><time className="text-xs text-[var(--muted)]">{new Date(`${match.date}T12:00:00`).toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" })}</time></div><h2 className="mt-3 text-lg font-bold">{match.homeTeam} <span className="text-[var(--muted)]">vs</span> {match.awayTeam}</h2><p className="mt-1 text-sm text-[var(--muted)]">{match.location} · {match.overs} overs</p><button className="mt-4 min-h-10 w-full rounded-xl border border-[var(--line)] text-sm font-bold text-[var(--brand)]">{match.status === "Upcoming" ? "Select teams" : match.status === "Live" ? "Continue scoring" : "View scorecard"}</button></article>) : <EmptyState title="No matches here yet" description="Create your next fixture and bring the weekend cricket crew together." />}</div>
    {isFormOpen && <div className="fixed inset-0 z-30 flex items-end bg-black/35 sm:items-center sm:justify-center sm:p-4"><form onSubmit={submitMatch} className="w-full rounded-t-3xl bg-white p-5 shadow-2xl sm:max-w-md sm:rounded-3xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">Create match</h2><button type="button" onClick={() => setIsFormOpen(false)} className="p-2 text-[var(--muted)]" aria-label="Close">✕</button></div><Field label="Team A" value={form.homeTeam} onChange={(value) => setForm({ ...form, homeTeam: value })} /><Field label="Team B" value={form.awayTeam} onChange={(value) => setForm({ ...form, awayTeam: value })} placeholder="e.g. Sunday Strikers" /><div className="mt-4 grid grid-cols-2 gap-3"><Field label="Match date" type="date" value={form.date} onChange={(value) => setForm({ ...form, date: value })} /><Field label="Overs" type="number" value={String(form.overs)} onChange={(value) => setForm({ ...form, overs: Number(value) || 0 })} /></div><Field label="Location" value={form.location} onChange={(value) => setForm({ ...form, location: value })} placeholder="e.g. Riverside Ground" /><div className="mt-6 flex gap-3"><button type="button" onClick={() => setIsFormOpen(false)} className="min-h-11 flex-1 rounded-xl border border-[var(--line)] text-sm font-bold">Cancel</button><button className="min-h-11 flex-1 rounded-xl bg-[var(--brand)] text-sm font-bold text-white">Create match</button></div></form></div>}
  </>;
}

function Field({ label, value, onChange, type = "text", placeholder }: { label: string; value: string; onChange: (value: string) => void; type?: "text" | "date" | "number"; placeholder?: string }) { return <label className="mt-4 block text-sm font-semibold">{label}<input required type={type} min={type === "number" ? 1 : undefined} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-1.5 min-h-11 w-full rounded-xl border border-[var(--line)] px-3 font-normal outline-none focus:border-[var(--brand)]" /></label>; }
